name: connections
description: A social network for communities
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.1.2
  http: ^1.2.0
  http_parser: ^4.0.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.17+1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.4.0
  flutter_launcher_icons: ^0.14.3

  # 🔥 New Packages for Chat Enhancements
  emoji_picker_flutter: ^2.2.0
  file_picker: ^8.0.5
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  mime: ^1.0.5
  open_filex: ^4.4.0 # (Optional but recommended for opening attachments)

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
