name: tern
description: A social network for communities
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  http_parser: ^4.0.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.17+1
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.4.0 # For WebSocket communication
  flutter_launcher_icons: "^0.14.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Android Icons/192x192.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/Chrome Store/128x128.png"
    background_color: "white"
    theme_color: "white"
  windows:
    generate: true
    image_path: "assets/icons/Windows/Square310x310Logo.scale-400.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"